# -*- mode: ruby -*-
# vi: set ft=ruby :
VM_NAME = "sdwa"
HOST_PORT = 5000

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine313"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 5000, host: HOST_PORT
  config.vm.define VM_NAME
  config.vm.hostname = VM_NAME
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.name = VM_NAME
    v.memory = 256
    v.cpus = 1
  end
  config.vm.provision "shell", inline: <<-SHELL
    /bin/bash
    sudo apk update
    sudo apk add git python3 py3-pip gcc python3-dev libevent-dev musl-dev linux-headers g++ 
    if [ ! -f /usr/bin/python ]
      then
      sudo ln -s /usr/bin/python3 /usr/bin/python
    fi
    if [ $(grep -c "/.local/bin" /etc/profile) -ne 1 ]
      then
      sudo -- sh -c -e "echo 'export PATH=/home/vagrant/.local/bin:$PATH' >> /etc/profile"
      source /etc/profile
    fi
    if [ ! -d /home/vagrant/sdwa ]
      then
      git clone https://github.com/StackZeroSec/sdwa.git
      sudo chown -R vagrant:vagrant sdwa/
      cd sdwa
      pip install -r requirements.txt
      rm db/vuln_db.sqlite
      python db/setup_db.py
      cd ..
    fi
    cd /home/vagrant/sdwa
    flask run --host=0.0.0.0 --no-debugger --no-reload --without-threads
    sudo pkill flask
    echo "Web Server stopped"
    sudo poweroff
  SHELL
end
