# -*- mode: ruby -*-
# vi: set ft=ruby :
VM_NAME = "sdwa"
HOST_PORT = 5000

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine313"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 5000, host: HOST_PORT
  config.vm.define VM_NAME
  config.vm.hostname = VM_NAME
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.name = VM_NAME
    v.memory = 256
    v.cpus = 1
    vb.customize ["modifyvm", :id, "--vram", "9"]
  end
  config.vm.provision "shell", path: "config.sh"
  config.vm.synced_folder "proj/", "/home/vagrant/proj/"
end
