# -*- mode: ruby -*-
# vi: set ft=ruby :
VM_NAME = "VHDL"
SSH_PORT = 2222

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-11.2"
    config.vm.box_check_update = false
    config.vm.network :forwarded_port, guest: 22, host: SSH_PORT, id: 'ssh'
    config.vm.define VM_NAME
    config.vm.hostname = VM_NAME
    config.vm.provider "virtualbox" do |vb|
      v.gui = false
      vb.name = VM_NAME
      vb.memory = 512
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--vram", "9"]
    end
    config.vm.provision "shell", path: "config.sh"
    config.vm.synced_folder "proj/", "/home/vagrant/proj/"
  end